### PR TITLE
figures for analysis part

### PR DESCRIPTION
**Pull request by pojeda**
added two figures. @robertodr

### CODE REVIEW

**Review by robertodr — COMMENTED** [review]
Uhm, why did these commits remove the RMA exercises?

**Comment by pojeda** [comment]
rma are not removed, the folders were renamed in the process when I merged my old branch pojeda into po-part.

**Comment by pojeda** [comment]
rma exercises are duplicated in the master branch

**Comment by pojeda** [comment]
any recommendation on how to proceed @robertodr ?  /Pedro

**Pull request merged**
