### PR TITLE
Update schedule for day 2

### PR DESCRIPTION
**Pull request by mabraham**

### CODE REVIEW

**Comment by mabraham** [comment]
@wikfeldt Can we update https://enccs.se/events/2020/intermediate-topics-in-mpi/ also, please? It still has day 2 and 3 in the wrong order

**Comment by wikfeldt** [comment]
> @wikfeldt Can we update https://enccs.se/events/2020/intermediate-topics-in-mpi/ also, please? It still has day 2 and 3 in the wrong order

yes, sorry i missed that. Asked Apostolos to swap

**Review by wikfeldt — COMMENTED** [review]
good to have many breaks but i'm wondering if a 10 minute break would be good to have in the middle. Would that be possible? Cutting down the wrap-up time to 5 minute would be ok

**Comment by mabraham** [comment]
Yeah, I'm sure we can. I'm guessing on time lengths, having not actually practiced...

**Review by wikfeldt — APPROVED** [review]
thanks!

**Pull request merged**
