### PR TITLE
.github/workflows/sphinx: sync with upstream

### PR DESCRIPTION
**Pull request by rkdarst**
- This adds in some debugging information about versions of packages.

### CODE REVIEW

**Review by mabraham — APPROVED** [review]

**Comment by robertodr** [comment]
Thanks! This is what I see in the output:
```
+ git rev-parse --abbrev-ref HEAD
github.ref: refs/pull/42/merge
github.event_name: pull_request
github.head_ref: rkdarst/update-sphinx-action
github.base_ref: master
HEAD
+ git branch
* (HEAD detached at pull/42/merge)
+ git branch -a
* (HEAD detached at pull/42/merge)
  remotes/origin/gh-pages
  remotes/origin/master
  remotes/origin/mja-threading
  remotes/origin/rdr-derived-datatypes
  remotes/pull/42/merge
+ git remote -v
origin	https://github.com/ENCCS/intermediate-mpi (fetch)
origin	https://github.com/ENCCS/intermediate-mpi (push)
+ python -V
Python 3.8.6
+ pip list --not-required
Package              Version
-------------------- -------
pip                  20.2.4
sphinx-book-theme    0.0.39
sphinx-lesson        0.8.3
sphinxcontrib-bibtex 1.0.0
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip' command.
+ pip list
Package                             Version
----------------------------------- ---------
alabaster                           0.7.12
argon2-cffi                         20.1.0
async-generator                     1.10
attrs                               20.3.0
Babel                               2.9.0
backcall                            0.2.0
beautifulsoup4                      4.9.3
bleach                              3.2.1
certifi                             2020.12.5
cffi                                1.14.4
chardet                             3.0.4
click                               7.1.2
colorama                            0.4.4
decorator                           4.4.2
defusedxml                          0.6.0
docutils                            0.16
entrypoints                         0.3
gitdb                               4.0.5
GitPython                           3.1.11
idna                                2.10
imagesize                           1.2.0
importlib-metadata                  3.1.1
ipykernel                           5.3.4
ipython                             7.19.0
ipython-genutils                    0.2.0
ipywidgets                          7.5.1
jedi                                0.17.2
Jinja2                              2.11.2
jsonschema                          3.2.0
jupyter-cache                       0.4.1
jupyter-client                      6.1.7
jupyter-core                        4.7.0
jupyter-sphinx                      0.3.2
latexcodec                          2.0.1
livereload                          2.6.3
markdown-it-py                      0.5.6
MarkupSafe                          1.1.1
mistune                             0.8.4
myst-nb                             0.10.1
myst-parser                         0.12.10
nbclient                            0.5.1
nbconvert                           5.6.1
nbdime                              2.1.0
nbformat                            5.0.8
nest-asyncio                        1.4.3
notebook                            6.1.5
oset                                0.1.3
packaging                           20.7
pandocfilters                       1.4.3
parso                               0.7.1
pexpect                             4.8.0
pickleshare                         0.7.5
pip                                 20.2.4
prometheus-client                   0.9.0
prompt-toolkit                      3.0.8
ptyprocess                          0.6.0
pybtex                              0.23.0
pybtex-docutils                     0.2.2
pycparser                           2.20
pydata-sphinx-theme                 0.4.1
Pygments                            2.7.3
pyparsing                           2.4.7
pyrsistent                          0.17.3
python-dateutil                     2.8.1
pytz                                2020.4
PyYAML                              5.3.1
pyzmq                               20.0.0
requests                            2.25.0
Send2Trash                          1.5.0
setuptools                          49.2.1
six                                 1.15.0
smmap                               3.0.4
snowballstemmer                     2.0.0
soupsieve                           2.0.1
Sphinx                              3.3.1
sphinx-autobuild                    2020.9.1
sphinx-book-theme                   0.0.39
sphinx-copybutton                   0.3.1
sphinx-lesson                       0.8.3
sphinx-minipres                     0.2.1
sphinx-rtd-theme                    0.5.0
sphinx-rtd-theme-ext-color-contrast 0.2.0
sphinx-tabs                         1.3.0
sphinx-togglebutton                 0.2.3
sphinxcontrib-applehelp             1.0.2
sphinxcontrib-bibtex                1.0.0
sphinxcontrib-devhelp               1.0.2
sphinxcontrib-htmlhelp              1.0.3
sphinxcontrib-jsmath                1.0.1
sphinxcontrib-qthelp                1.0.3
sphinxcontrib-serializinghtml       1.1.4
SQLAlchemy                          1.3.20
terminado                           0.9.1
testpath                            0.4.4
tornado                             6.1
traitlets                           5.0.5
urllib3                             1.26.2
wcwidth                             0.2.5
webencodings                        0.5.1
wheel                               0.36.1
widgetsnbextension                  3.5.1
zipp                                3.4.0
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.8.6/x64/bin/python -m pip install --upgrade pip' command.
```

**Comment by rkdarst** [comment]
Update!

* `make html` works on the main page
* `make dirhtml` fails on the main page

Also `index.rst` is the only document which keeps its name: all other
get renamed to `index.html` and put into a sub-directory, to have
pretty URLs.  This isn't the first error of an executablebooks project
for the dirhtml builder, but I can't yet see how it could be a problem
of sphinx-copybutton itself... I will investigate more.

**Comment by robertodr** [comment]
A-ha! Thanks for the detective work! So if we renamed `index.rst` to something else it would fix the problem?

**Comment by rkdarst** [comment]
(oops, I replied to the wrong thing.  Moving to the right issue)

**Pull request merged**
